Updated README.md

diff --git a/build b/build
--- a/build
+++ b/build
@@ -5,40 +5,36 @@ github_download_release_asset() {
   local repository=$2
   local tagName=$3
   local assetName=$4
-  local destPath=$5
 
-  pushd ${destPath} > /dev/null
-  is_200_ok=$(wget -q --show-progress --server-response https://github.com/${owner}/${repository}/releases/download/${tagName}/${assetName} 2>&1| grep -c 'HTTP/1.1 200 OK')
+  is_200_ok=$(wget -q --show-progress --server-response https://github.com/${owner}/${repository}/releases/download/${tagName}/${assetName} 2>&1 | grep -c 'HTTP/1.1 200 OK')
   if [ $is_200_ok != "1" ]; then
     echo "Failed to get ${assetName}"
     exit 1
   fi
-  popd > /dev/null
 }
 
 download_from_url() {
-  local url=$1
-  local destPath=$2
-
-  wget -q --show-progress -O "${destPath}" ${url}
+  local assetName=$1
+  is_200_ok=$(wget -q --show-progress --server-response ${1} 2>&1 | grep -c 'HTTP/1.1 200 OK')
+  if [ $is_200_ok != "1" ]; then
+    echo "Failed to get ${assetName}"
+    exit 1
+  fi
 }
 
 process_external_download() {
   local url=$1
   local filename=$2
-  local destPath=$3
-  local destFilename=${destPath}/${filename}
 
-  echo Downloading \"${url}\" to \"${destFilename}\"
+  echo Downloading \"${url}\"
 
-  download_from_url ${url} ${destFilename}
+  download_from_url ${url}
 }
 
 process_github_release_asset_download() {
   local owner=$1
   local repository=$2
   local assetName=$3
-  local destPath=$4
 
   if [ $releaseType == "dev" ]; then
     tagName="latest-rc"
@@ -48,18 +44,27 @@ process_github_release_asset_download() {
     tagName="latest"
   fi
 
-  echo Downloading \"${owner}/${repository}@${tagName}/${assetName}\" to \"${destPath}/$assetName\"
+  echo Downloading \"${owner}/${repository}@${tagName}/${assetName}\"
 
-  github_download_release_asset ${owner} ${repository} ${tagName} ${assetName} ${destPath}
+  github_download_release_asset ${owner} ${repository} ${tagName} ${assetName}
 }
 
 extract() {
-  local fileType=${1}
-  local fileName=${2}
-  echo Extracting ${fileName}
-  extract_${fileType} ${fileName}
-  rm -f ${fileName}
+  local fileName=${1}
+  case "$fileName" in
+  *.zip)
+    echo Extracting ${fileName}
+    extract_zip ${fileName}
+    rm -f ${assetFilename}
+    ;;
+  *.tar)
+    echo Extracting ${fileName}
+    extract_tar ${fileName}
+    rm -f ${assetFilename}
+    ;;
+  esac
 }
+
 extract_zip() {
   unzip -qq ${1}
 }
@@ -69,63 +74,37 @@ extract_tar() {
 }
 
 process_build_file() {
-  local buildFilePath=$1
+  local buildType=$1
+  local buildFilePath=.build
   local source=$(cat ${buildFilePath} | jq -r ".source")
-  local destinationPath=$(dirname ${buildFilePath})
   local assetFilename=""
 
   if [ "${source}" == "external" ]; then
     local url=$(cat ${buildFilePath} | jq -r ".url")
     assetFilename=$(cat ${buildFilePath} | jq -r ".filename")
-    process_external_download ${url} ${assetFilename} ${destinationPath}
+    process_external_download ${url} ${assetFilename}
 
   elif [ "${source}" == "github-release-asset" ]; then
     local owner=$(cat ${buildFilePath} | jq -r ".owner")
     local repository=$(cat ${buildFilePath} | jq -r ".repository")
     assetFilename=$(cat ${buildFilePath} | jq -r ".assetName")
-    process_github_release_asset_download ${owner} ${repository} ${assetFilename} ${destinationPath}
+    process_github_release_asset_download ${owner} ${repository} ${assetFilename}
   fi
 
+  rm $buildFilePath
+
   if [[ ! -z ${assetFilename} ]]; then
-    pushd ${destinationPath} > /dev/null
-    case "$assetFilename" in
-    *.zip)
-      extract zip ${assetFilename}
-      ;;
-    *.tar)
-      extract tar ${assetFilename}
-      ;;
-    esac
-    echo Cleaning Up ${destinationPath}
-    rm .build
-    popd > /dev/null
+    extract ${assetFilename}
+  fi
+
+  if [ -d "uclibc" ]; then
+    cp uclibc/* .
+    rm -rf libc uclibc
   fi
 }
 
 clean() {
   echo "Cleaning..."
-
-  # shopt -s globstar
-  # for buildFile in ./**/.build
-  # do
-  #   local dirname=`dirname ${buildFile}`
-
-  #   echo "Cleaning ${dirname}"
-
-  #   local deleteArray=(`cat ${buildFile} | jq -c ".assetName"`)
-  #   local deleteRules=`cat ${buildFile} | jq -c ".clean"`
-
-  #   if [ ${deleteRules} != "null" ]; then
-  #     deleteArray=(`cat ${buildFile} | jq ".clean[]"`)
-  #   fi
-
-  #   for file in "${deleteArray[@]}"; do
-  #     rm -rf ${dirname}/${file:1:-1}
-  #   done
-
-  # done
-
-  echo "Cleaning package"
   rm -rf dist
 }
 
@@ -135,14 +114,16 @@ build() {
   cp -r sdcard/* dist/
   shopt -s globstar
   for buildFile in dist/**/.build; do
-    process_build_file ${buildFile}
+    pushd $(dirname ${buildFile})
+    process_build_file ${1}
+    popd
   done
 }
 
 package() {
-  pushd dist > /dev/null
-  zip -r sdcard.zip * -x hacks/**/.build
-  popd > /dev/null
+  pushd dist
+  zip -r sdcard_$1.zip * -x hacks/**/libc -x hacks/**/uclibc
+  popd
 }
 
 main() {
